export type UserRole =
  | 'admin'
  | 'admin_order'
  | 'admin_regulatory'
  | 'finances'
  | 'operator'
  | 'customer'
  | 'shopper'
  | 'regulatory_manager'
  | 'regulatory_manager_distributor'
  | 'storage'
  | 'delivery_man'
  | 'portfolio_manager'
  | 'admin_finances'
  | 'internal'
  | 'pharmacy_sells'
  | 'permission_manager';
